### ISSUE TITLE
Broken Links in the Ruby Section

### ISSUE THREAD

**Issue by flounders** [unicodeveloper/awesome-tdd#4]
Line 128: [Learn TDD by Practicing 7 Katas](https://www.udemy.com/learn-test-driven-development-in-ruby/) This one "works", but the course is no longer available for access except to those who have purchased it.

Line 131: [TDD with Ruby and Rspec](https://github.com/zachtblake/tdd_ruby) This one yields a 404, and the user doesn't seem to exist on GitHub.

I have submitted a pull request that addresses this temporarily. https://github.com/unicodeveloper/awesome-tdd/pull/3

**Comment by unicodeveloper** [comment]
Thanks for the PR. Merged. I'll close this issue now.
